name: easacc
description: "Task Demo App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.2
  network_info_plus: ^4.0.0
  network_port_scanner: ^1.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
